"""Internal runtime-agnostic membrane Model IR.

This package is the neutral semantic layer for the active DSL/compiler work. It
is intentionally independent from JAX execution; public simulations still enter
through ``AxonSimulation`` and the current JAX runtime until the lowering is
ready.
"""

from .program import (
    MembraneNameGroups,
    MembraneProgram,
    conductance_name,
    conductance_parameter_name,
    group_name_indices,
    membrane_program_from_model_ir,
    symbol_names,
)
from .composition import compose_model_ir, rewrite_symbols
from .expressions import BinaryOp, Call, Expression, Literal, Symbol, literal, symbol
from .fusion import ModelStepContract, OutputPruningPlan, derive_model_step_contract
from .intrinsics import DEFAULT_INTRINSICS, Intrinsic, IntrinsicRegistry, call
from .interpreter import (
    NumpyMembraneStepPlan,
    NumpyModelInterpreter,
    NumpyModelStep,
    evaluate_expression_np,
)
from .schema import (
    Current,
    Diagnostic,
    FunctionDef,
    Gate,
    GateUpdateKind,
    Input,
    KineticBlock,
    KineticInitialization,
    KineticTransition,
    KineticUpdateKind,
    LinearizationGateSource,
    ModelIR,
    MODEL_IR_SCHEMA_VERSION,
    Observable,
    Parameter,
    QuantitySpec,
    SCALAR_SHAPE,
    SemanticRole,
    ShapeSpec,
    State,
    StateUpdate,
    StepProgram,
    SymbolKind,
    Variability,
)
from .serialization import (
    canonical_json,
    expression_from_data,
    model_ir_from_data,
    model_ir_from_json,
    parameterized_hash,
    structural_hash,
)
from .source import (
    GeneratedCodeCache,
    SourceModelCompileError,
    SourceModelCompileResult,
    compile_model_source_file,
)
from .validation import (
    ModelValidationError,
    ValidationIssue,
    assert_valid_model_ir,
    validate_model_ir,
)

__all__ = [
    "BinaryOp",
    "Call",
    "Current",
    "DEFAULT_INTRINSICS",
    "Diagnostic",
    "Expression",
    "FunctionDef",
    "Gate",
    "GateUpdateKind",
    "GeneratedCodeCache",
    "Input",
    "KineticBlock",
    "KineticInitialization",
    "KineticTransition",
    "KineticUpdateKind",
    "Intrinsic",
    "IntrinsicRegistry",
    "LinearizationGateSource",
    "Literal",
    "MembraneNameGroups",
    "MembraneProgram",
    "MODEL_IR_SCHEMA_VERSION",
    "ModelIR",
    "ModelStepContract",
    "ModelValidationError",
    "NumpyModelInterpreter",
    "NumpyModelStep",
    "NumpyMembraneStepPlan",
    "Observable",
    "OutputPruningPlan",
    "Parameter",
    "QuantitySpec",
    "SCALAR_SHAPE",
    "SemanticRole",
    "ShapeSpec",
    "SourceModelCompileError",
    "SourceModelCompileResult",
    "State",
    "StateUpdate",
    "StepProgram",
    "Symbol",
    "SymbolKind",
    "ValidationIssue",
    "Variability",
    "assert_valid_model_ir",
    "call",
    "canonical_json",
    "compose_model_ir",
    "compile_model_source_file",
    "conductance_name",
    "conductance_parameter_name",
    "derive_model_step_contract",
    "expression_from_data",
    "evaluate_expression_np",
    "group_name_indices",
    "literal",
    "membrane_program_from_model_ir",
    "model_ir_from_data",
    "model_ir_from_json",
    "parameterized_hash",
    "rewrite_symbols",
    "structural_hash",
    "symbol",
    "symbol_names",
    "validate_model_ir",
]
