from .utils import units

from . import (
    analysis,
    analytical,
    axons,
    dispatcher,
    identifiers,
    inspection,
    membranes,
    performance,
    preparation,
    positions,
    protocols,
    results,
    runtime,
    signals,
    solvers,
    stimulation,
)
from axonscope.analysis import (
    Activation,
    ActivationObserver,
    AnalysisInputRequirement,
    AnalysisPopulation,
    AnalysisReport,
    AnalysisRequirements,
    AnalysisResult,
    AnalysisStatus,
    ConductionBlock,
    ConductionVelocity,
    Latency,
    PeakVoltage,
    SpikeCount,
    SpikeCountEvent,
)
from axonscope.axon_instance import AxonInstance
from axonscope.benchmarking import (
    BenchmarkOptions,
    BenchmarkReport,
    BenchmarkSession,
    benchmark,
    benchmark_report,
    disable_benchmark,
    enable_benchmark,
    reset_benchmark,
)
from axonscope.identifiers import AxonId, DriveId, SignalId
from axonscope.inspection import (
    AssemblyDetailInspection,
    DispatchGroupInspection,
    KernelInspection,
    LoweringInspection,
    MemoryInspection,
    MembraneSourceInspection,
    PaddingInspection,
    PlanningInspection,
    ProbeInspection,
    PreparationInspection,
    ResultAssemblyInspection,
    SimulationInspection,
)
from axonscope.performance import (
    MemoryEstimateItem,
    SimulationEstimate,
    SimulationEstimateGroup,
)
from axonscope.population import AxonPopulation
from axonscope.results import (
    AxonResultView,
    AxonSimulationResult,
    RecordedAxis,
    RecordedSignal,
    RecordingManifest,
    VM_RASTER_OBSERVATION_KEY,
    VmRasterResult,
    unpack_vm_raster_words,
)
from axonscope.recording import Recording, RecordingPlan, RecordingSpatial
from axonscope.runtime import (
    CableSolverRoute,
    Device,
    ExecutionPolicy,
    PrecisionPolicy,
    RuntimeSolverRoute,
    SolverPolicy,
)
from axonscope.signals import Signal
from axonscope.simulation import AxonSimulation
from axonscope.solvers import (
    BatchOptions,
    BatchRecording,
    DEFAULT_OBSERVER_TIME_CHUNK_STEPS,
    SolverOptions,
)
from axonscope.stimulation import (
    ExtracellularDrive,
    ExtracellularFootprint,
    ExtracellularPotential,
    ExtracellularStimulation,
    IntracellularContext,
    IntracellularCurrentClamp,
)
from axonscope.stimulation import Stimulus

__version__ = "0.1.0"

_UNIT_ALIASES = {
    "A": "ampere",
    "cm": "centimeter",
    "degC": "degree_Celsius",
    "Hz": "hertz",
    "kHz": "kilohertz",
    "m": "meter",
    "mA": "milliampere",
    "mM": "millimolar",
    "mS": "millisiemens",
    "mA_per_cm2": "milliampere / centimeter ** 2",
    "MOhm_per_cm": "megaohm / centimeter",
    "mV": "millivolt",
    "mm": "millimeter",
    "ms": "millisecond",
    "nA": "nanoampere",
    "ohm": "ohm",
    "ohm_cm": "ohm * centimeter",
    "ohm_cm2": "ohm * centimeter ** 2",
    "ohm_um": "ohm * micrometer",
    "s": "second",
    "S": "siemens",
    "S_per_cm2": "siemens / centimeter ** 2",
    "S_per_m": "siemens / meter",
    "S_per_meter": "siemens / meter",
    "siemens_per_m": "siemens / meter",
    "siemens_per_meter": "siemens / meter",
    "mS_per_cm": "millisiemens / centimeter",
    "mS_per_cm2": "millisiemens / centimeter ** 2",
    "mS_per_centimeter": "millisiemens / centimeter",
    "uA": "microampere",
    "uF": "microfarad",
    "uF_per_cm2": "microfarad / centimeter ** 2",
    "um": "micrometer",
    "us": "microsecond",
    "V": "volt",
}


def __getattr__(name: str):
    if name in _UNIT_ALIASES:
        return getattr(units.ureg, _UNIT_ALIASES[name])
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = [
    "__version__",
    "analysis",
    "analytical",
    "axons",
    "dispatcher",
    "identifiers",
    "inspection",
    "membranes",
    "performance",
    "preparation",
    "positions",
    "protocols",
    "results",
    "runtime",
    "signals",
    "solvers",
    "stimulation",
    "units",
    "Stimulus",
    "Activation",
    "ActivationObserver",
    "AnalysisInputRequirement",
    "AnalysisPopulation",
    "AnalysisReport",
    "AnalysisRequirements",
    "AnalysisResult",
    "AnalysisStatus",
    "ConductionBlock",
    "ConductionVelocity",
    "Latency",
    "PeakVoltage",
    "SpikeCount",
    "SpikeCountEvent",
    "AxonId",
    "DriveId",
    "SignalId",
    "AssemblyDetailInspection",
    "DispatchGroupInspection",
    "KernelInspection",
    "LoweringInspection",
    "MemoryInspection",
    "MembraneSourceInspection",
    "PaddingInspection",
    "PlanningInspection",
    "ProbeInspection",
    "PreparationInspection",
    "ResultAssemblyInspection",
    "SimulationInspection",
    "CableSolverRoute",
    "Device",
    "ExecutionPolicy",
    "MemoryEstimateItem",
    "PrecisionPolicy",
    "RuntimeSolverRoute",
    "SimulationEstimate",
    "SimulationEstimateGroup",
    "SolverPolicy",
    "AxonInstance",
    "BenchmarkReport",
    "BenchmarkOptions",
    "BenchmarkSession",
    "AxonPopulation",
    "AxonSimulation",
    "benchmark",
    "benchmark_report",
    "disable_benchmark",
    "enable_benchmark",
    "reset_benchmark",
    "BatchOptions",
    "BatchRecording",
    "DEFAULT_OBSERVER_TIME_CHUNK_STEPS",
    "SolverOptions",
    "Recording",
    "RecordingPlan",
    "RecordingSpatial",
    "Signal",
    "IntracellularContext",
    "IntracellularCurrentClamp",
    "ExtracellularDrive",
    "ExtracellularFootprint",
    "ExtracellularPotential",
    "ExtracellularStimulation",
    "VM_RASTER_OBSERVATION_KEY",
    "VmRasterResult",
    "AxonResultView",
    "AxonSimulationResult",
    "RecordedAxis",
    "RecordedSignal",
    "RecordingManifest",
    "unpack_vm_raster_words",
    *_UNIT_ALIASES,
]
