from __future__ import annotations

import axonfleet as axs
from axonfleet.membranes.generated_code import GeneratedMembraneCodeReport


def test_membrane_model_inspects_generated_code_cache_and_files(tmp_path, monkeypatch):
    monkeypatch.setenv("AXONFLEET_CACHE", str(tmp_path / "codegen"))
    model = axs.membranes.Passive()

    report = model.inspect_generated_code()

    assert isinstance(report, GeneratedMembraneCodeReport)
    assert report.model_kind == "passive"
    assert len(report.sources) == 1
    source = report.sources[0]
    assert source.model_name == "passive"
    assert source.cache_status in {"hit", "miss"}
    assert source.cache_reason in {
        "manifest_match",
        "manifest_missing",
        "generated_files_missing:jax_model.py,numpy_model.py",
    }
    assert source.source_hash
    assert len(source.graph_hash) == 40
    assert source.optimized_graph_hash == source.graph_hash
    assert source.cache_key
    assert source.manifest["cache_key"] == source.cache_key
    assert {generated.name for generated in source.files} == {
        "source_snapshot.py",
        "graph.json",
        "optimized_graph.json",
        "jax_model.py",
        "numpy_model.py",
    }
    assert source.file("jax_model.py").read_text().startswith(
        "# Generated by AxonFleet."
    )

    text = report.format()
    assert "AxonFleet generated membrane code" in text
    assert "model=passive" in text
    assert f"graph_hash={source.graph_hash}" in text
    assert f"optimized_graph_hash={source.optimized_graph_hash}" in text
    assert f"cache={source.cache_status}, reason={source.cache_reason}" in text
    assert "jax_model.py" in text
    assert "numpy_model.py" in text


def test_membrane_generated_code_report_can_include_selected_text(tmp_path, monkeypatch):
    monkeypatch.setenv("AXONFLEET_CACHE", str(tmp_path / "codegen"))
    model = axs.membranes.Passive()
    model.inspect_generated_code()

    report = axs.membranes.inspect_generated_code(
        model,
        include_text=True,
        files=("jax_model.py",),
        max_text_chars=2000,
    )

    source = report.sources[0]
    assert source.cache_status == "hit"
    assert source.cache_reason == "manifest_match"
    assert tuple(generated.name for generated in source.files) == ("jax_model.py",)
    assert source.files[0].text is not None
    assert "CACHE_KEY" in source.files[0].text
    assert "def model_step" in source.files[0].text
    assert "text:" in report.format()


def test_membrane_generated_code_report_explains_corrupt_manifest(tmp_path, monkeypatch):
    monkeypatch.setenv("AXONFLEET_CACHE", str(tmp_path / "codegen"))
    model = axs.membranes.Passive()
    first = model.inspect_generated_code()
    manifest_path = first.sources[0].manifest_path

    with open(manifest_path, "w", encoding="utf-8") as handle:
        handle.write("{not-json")

    second = model.inspect_generated_code()

    assert second.sources[0].cache_status == "miss"
    assert second.sources[0].cache_reason == "manifest_invalid_json"
    assert second.sources[0].manifest["cache_key"] == second.sources[0].cache_key
